version: '3'
services:
  # Node.js + Express Application
  node-app:
    build: ./node-app
    image: node-app
    ports:
      - "3000:3000"
    volumes:
      - "./node-app/src:/node-app"
      # This will map /node-app/node_modules to an anonymous volume maintained by docker
      # 'docker volume ls' -> long UUID
      - /node-app/node_modules
  # PM2 Process Deamon for Node.js + Express Application
  process-manager:
    image: keymetrics/pm2
  # Reverse Proxy Web Server
  nginx:
    build: ./nginx/
    image: nginx
    ports:
      - "80:80"
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/conf.d/default.conf"